global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers: []

rule_files: []

scrape_configs:
  # Prometheus 自己
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter（服务器 CPU/内存/磁盘/网络）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor（容器 CPU/内存/网络/磁盘）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 监控你自己写的 app（容器名或 IP）
  - job_name: 'devops-app'
    static_configs:
      - targets: ['devops-app:80']
